name: check
on:
#   push:
#     branches:
#       - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  centos7:
    name: Docker on centos7
    runs-on: ubuntu-18.04
    env:
      SCRIPT_URL: https://gitee.com/Xiechengqi/scripts/raw/master/install
    steps:
      - name: Docker
        run: |
          sudo docker run -itd --privileged --name centos7 centos:7 /sbin/init
          sudo docker exec centos7 /bin/bash -c '/bin/curl -SsL https://gitee.com/Xiechengqi/scripts/raw/master/install/Docker/install.sh | bash && sleep 10 && systemctl status docker'          
  centos8:
    name: Docker on centos8
    runs-on: ubuntu-18.04
    env:
      SCRIPT_URL: https://gitee.com/Xiechengqi/scripts/raw/master/install
    steps:
      - name: Docker
        run: |
          sudo docker run -itd --privileged --name centos8 centos:8 /sbin/init
          sudo docker exec centos8 /bin/bash -c '/bin/curl -SsL https://gitee.com/Xiechengqi/scripts/raw/master/install/Docker/install.sh | bash && sleep 10 && systemctl status docker'    
