name: Test Tools Install Scripts
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'
jobs:
  ubuntu-2004:
    name: verify on ubuntu:20.04
    runs-on: ubuntu-20.04
    env:
      SCRIPT_URL: https://gitee.com/Xiechengqi/scripts/raw/master/install
    steps:
      - name: docker
        run: |
          sudo systemctl stop docker && curl -SsL $SCRIPT_URL/Docker/install.sh | sudo bash || true
      - name: docker-compose 
        run: |
          sudo rm -f `which docker-compose` && curl -SsL $SCRIPT_URL/Docker/docker-compose/install.sh | sudo bash || true
      - name: node
        run: |
          sudo rm -f `which node` && curl -SsL $SCRIPT_URL/Node/install.sh | sudo bash || true
      - name: golang
        run: |
          sudo rm -f `which go` && curl -SsL $SCRIPT_URL/Golang/install.sh | sudo bash || true
      - name: ntp
        run: |
          curl -SsL $SCRIPT_URL/Ntp/install.sh | sudo bash || true
      - name: pyenv
        run: |
          curl -SsL $SCRIPT_URL/Pyenv/install.sh | sudo bash || true
      - name: check
        run: |
          sudo ss -plunt
          sudo apt install -q -y tree && sudo tree -d -L 3 /data
          echo "🍏 Ubuntu 20.04 is ${{ job.status }}"
#   Ubuntu-1804:
#     runs-on: ubuntu-18.04
#     steps:
#       - name: docker
#         run: |
#           sudo systemctl stop docker && curl -SsL https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/Docker/install.sh | sudo bash || true
#       - name: docker-compose 
#         run: |
#           sudo rm -f `which docker-compose` && curl -SsL https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/Docker/docker-compose/install.sh | sudo bash || true
#       - name: node
#         run: |
#           sudo rm -f `which node` && curl -SsL https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/Node/install.sh | sudo bash || true
#       - name: golang
#         run: |
#           sudo rm -f `which go` && curl -SsL https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/Golang/install.sh | sudo bash || true
#       - name: ntp
#         run: |
#           curl -SsL https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/Ntp/install.sh | sudo bash || true
#       - name: pyenv
#         run: |
#           curl -SsL https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/Pyenv/install.sh | sudo bash || true
#       - name: check
#         run: |
#           sudo ss -plunt
#           sudo apt install -q -y tree && sudo tree -d -L 3 /data
#           echo "🍏 Ubuntu 18.04 is ${{ job.status }}"
