name: check
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  ubuntu-1804:
    name: Mysql5.8 on ubuntu:18.04
    runs-on: ubuntu-18.04
    env:
      SCRIPT_URL: https://gitee.com/Xiechengqi/scripts/raw/master/install
    steps:
      - name: Mysql5.8
        run: |
          curl -SsL $SCRIPT_URL/Mysql/install.sh | sudo bash -s 5.8
      - name: check
        run: |
          sleep 10
          sudo systemctl status mysqld
          sudo ss -plunt
          sudo ls --color=auto -alht /data/*
          echo "🍏 Mysql5.8 Ubuntu 18.04 install script is ${{ job.status }}"
  ubuntu-2004:
    name: Mysql5.8 on ubuntu:20.04
    runs-on: ubuntu-20.04
    env:
      SCRIPT_URL: https://gitee.com/Xiechengqi/scripts/raw/master/install
    steps:
      - name: Mysql5.8
        run: |
          curl -SsL $SCRIPT_URL/Mysql/install.sh | sudo bash -s 5.8
      - name: check
        run: |
          sleep 10
          sudo systemctl status mysqld
          sudo ss -plunt
          sudo ls --color=auto -alht /data/*
          echo "🍏 Mysql.5.8 Ubuntu 20.04 install script is ${{ job.status }}"
