name: check
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  ubuntu-1804:
    name: Mysql8.0 on ubuntu:18.04
    runs-on: ubuntu-18.04
    env:
      SCRIPT_URL: https://gitee.com/Xiechengqi/scripts/raw/master/install
    steps:
      - name: Mysql8.0
        run: |
          sudo systemctl stop mysqld && curl -SsL $SCRIPT_URL/Mysql/install.sh | sudo bash -s 8.0
      - name: check
        run: |
          sleep 10
          sudo systemctl status mysqld
          sudo ss -plunt
          sudo ls --color=auto -alht /data/*
          echo "🍏 Mysql8.0 Ubuntu 18.04 install script is ${{ job.status }}"
  ubuntu-2004:
    name: Mysql8.0 on ubuntu:20.04
    runs-on: ubuntu-20.04
    env:
      SCRIPT_URL: https://gitee.com/Xiechengqi/scripts/raw/master/install
    steps:
      - name: Mysql8.0
        run: |
          sudo systemctl stop mysqld && curl -SsL $SCRIPT_URL/Mysql/install.sh | sudo bash -s 8.0
      - name: check
        run: |
          sleep 10
          sudo systemctl status mysqld
          sudo ss -plunt
          sudo ls --color=auto -alht /data/*
          echo "🍏 Mysql.8.0 Ubuntu 20.04 install script is ${{ job.status }}"
