name: check
on:
#   push:
#     branches:
#       - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  ubuntu-1804:
    name: Mongodb on ubuntu:18.04
    runs-on: ubuntu-18.04
    env:
      SCRIPT_URL: https://gitee.com/Xiechengqi/scripts/raw/master/install
    steps:
      - name: Mongodb
        run: |
          curl -SsL $SCRIPT_URL/Mongodb/install.sh | sudo bash
      - name: check
        run: |
          sleep 10
          sudo systemctl status mongod
          sudo ss -plunt
          sudo ls --color=auto -alht /data/*
          echo "🍏 Mongodb Ubuntu 18.04 install script is ${{ job.status }}"
  ubuntu-2004:
    name: Mongodb on ubuntu:20.04
    runs-on: ubuntu-20.04
    env:
      SCRIPT_URL: https://gitee.com/Xiechengqi/scripts/raw/master/install
    steps:
      - name: Mongodb
        run: |
          curl -SsL $SCRIPT_URL/Mongodb/install.sh | sudo bash
      - name: check
        run: |
          sleep 10
          sudo systemctl status mongod
          sudo ss -plunt
          sudo ls --color=auto -alht /data/*
          echo "🍏 Mongodb Ubuntu 20.04 install script is ${{ job.status }}"
